//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalChair.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesExceptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentalChair.Exceptions.ResourceMessagesExceptions", typeof(ResourceMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Allocation Not Found.
        /// </summary>
        public static string ALLOCATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("ALLOCATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chair(s) Not Found.
        /// </summary>
        public static string CHAIR_NOT_FOUND {
            get {
                return ResourceManager.GetString("CHAIR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Chair Number is Already Taken by Another Chair..
        /// </summary>
        public static string CHAIR_NUMBER_ALREADY_EXIST_IN_OTHER_CHAIR {
            get {
                return ResourceManager.GetString("CHAIR_NUMBER_ALREADY_EXIST_IN_OTHER_CHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Chair Number Already Registered.
        /// </summary>
        public static string CHAIR_NUMBER_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("CHAIR_NUMBER_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Chair Number Cannot be Empty..
        /// </summary>
        public static string CHAIR_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("CHAIR_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Dental Chair cannot be Empty.
        /// </summary>
        public static string DENTAL_CHAIR_EMPTY {
            get {
                return ResourceManager.GetString("DENTAL_CHAIR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Description Chair Cannot be Empty.
        /// </summary>
        public static string DESCRIPTION_CHAIR_EMPTY {
            get {
                return ResourceManager.GetString("DESCRIPTION_CHAIR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The End Date cannot be Empty.
        /// </summary>
        public static string END_DATE_EMPTY {
            get {
                return ResourceManager.GetString("END_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The End Date Must Be Later Than The Start Date..
        /// </summary>
        public static string END_DATE_GREATER_THAN {
            get {
                return ResourceManager.GetString("END_DATE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Model Chair Cannot be Empty.
        /// </summary>
        public static string MODEL_CHAIR_EMPTY {
            get {
                return ResourceManager.GetString("MODEL_CHAIR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are no seats available at the requested time..
        /// </summary>
        public static string NO_CHAIRS_AVAILABLE {
            get {
                return ResourceManager.GetString("NO_CHAIRS_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Patient Name Cannot be Empty .
        /// </summary>
        public static string PATIENT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PATIENT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The patient&apos;s name must have up to 200 letters..
        /// </summary>
        public static string PATIENT_NAME_MAX_LENGHT {
            get {
                return ResourceManager.GetString("PATIENT_NAME_MAX_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Procedure Type cannot be Empty.
        /// </summary>
        public static string PROCEDURE_TYPE_EMPTY {
            get {
                return ResourceManager.GetString("PROCEDURE_TYPE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Procedure Type must have up to 100 letters.
        /// </summary>
        public static string PROCEDURE_TYPE_MAX_LENGHT {
            get {
                return ResourceManager.GetString("PROCEDURE_TYPE_MAX_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Purchase Date cannot be Empty.
        /// </summary>
        public static string PURCHASE_DATE_EMPTY {
            get {
                return ResourceManager.GetString("PURCHASE_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Star Date Cannot be Empty.
        /// </summary>
        public static string STAR_DATE_EMPTY {
            get {
                return ResourceManager.GetString("STAR_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Start Date must be later than the current date..
        /// </summary>
        public static string STAR_DATE_GREATER_THAN {
            get {
                return ResourceManager.GetString("STAR_DATE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status Allocation Cannot Be Empty.
        /// </summary>
        public static string STATUS_ALLOCATION_EMPTY {
            get {
                return ResourceManager.GetString("STATUS_ALLOCATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status Allocation Not Supported.
        /// </summary>
        public static string STATUS_ALLOCATION_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("STATUS_ALLOCATION_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknow Error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
    }
}
